export const envConfig = {
  //API URL
  API_URL: process.env.NEXT_PUBLIC_API_URL,

  //Country States API URL
  COUNTRY_STATE_API_URL: process.env.NEXT_PUBLIC_COUNTRY_STATE_API_URL,
  COUNTRY_STATE_API_KEY: process.env.NEXT_PUBLIC_COUNTRY_STATE_API_KEY,

  //Firebase
  FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  FIREBASE_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,

  //IndexDB
  DB_NAME: process.env.NEXT_PUBLIC_DB_NAME,
  DB_VERSION: 1,
  STORE_NAME: process.env.NEXT_PUBLIC_STORE_NAME
} as const
